/*
 * Matemat controller
 * Ports list
 */

#define MATECON_PORT_DIGITAL_0 PA0
#define MATECON_PORT_DIGITAL_1 PA1
#define MATECON_PORT_DIGITAL_2 PA2
#define MATECON_PORT_DIGITAL_3 PA3
#define MATECON_PORT_COIN_A PA4
#define MATECON_PORT_COIN_B PA5
#define MATECON_PORT_COIN_C PA6
#define MATECON_PORT_COIN_D PA7

#define MATECON_PORT_USBID PB0
#define MATECON_PORT_SCK PB1
#define MATECON_PORT_MOSI PB2
#define MATECON_PORT_MISO PB3
/*#define MATECON_PORT_ PB4*/
#define MATECON_PORT_COIN_E PB5
#define MATECON_PORT_BILL_FULL PB6
#define MATECON_PORT_BILL_VALID PB7

#define MATECON_PORT_BILL_REJ PC0
#define MATECON_PORT_BILL_ACK PC1
#define MATECON_PORT_BILL_INH PC2
#define MATECON_PORT_BILL_ABN PC3
#define MATECON_PORT_BILL_BUSY PC4
#define MATECON_PORT_BILL_VEND3 PC5
#define MATECON_PORT_BILL_VEND2 PC6
#define MATECON_PORT_BILL_VEND1 PC7

#define MATECON_PORT_SCL PD0
#define MATECON_PORT_SDA PD1
#define MATECON_PORT_UART1_RX PD2
#define MATECON_PORT_UART1_TX PD3
#define MATECON_PORT_CAN_SLEEP PD4
/*#define MATECON_PORT_ PD5*/
/*#define MATECON_PORT_ PD6*/
/*#define MATECON_PORT_ PD7*/

#define MATECON_PORT_UART0_RX PE0
#define MATECON_PORT_UART0_TX PE1
#define MATECON_PORT_UART0_RTS PE2
#define MATECON_PORT_UART0_CTS PE3
#define MATECON_PORT_UART1_RTS PE4
#define MATECON_PORT_UART1_CTS PE5
#define MATECON_PORT_STROBE PE6
#define MATECON_PORT_ZERO_CROSS PE7

#define MATECON_PORT_ANALOG_0 PF0
#define MATECON_PORT_ANALOG_1 PF1
#define MATECON_PORT_ANALOG_2 PF2
#define MATECON_PORT_ANALOG_3 PF3
#define MATECON_PORT_JTAG_TCK PF4
#define MATECON_PORT_JTAG_TMS PF5
#define MATECON_PORT_JTAG_TDO PF6
#define MATECON_PORT_JTAG_TDI PF7

#define MATECON_PORT_LED_A PG0
#define MATECON_PORT_LED_B PG1
#define MATECON_PORT_LED_C PG2
#define MATECON_PORT_FLASH_EN PG3
/*#define MATECON_PORT_ PG4*/
